#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    if bld.env['LICENSE'] == 'gpl':
        elfInclude = '../runtime/libbfd'
    else:
        elfInclude = '../runtime/libelf'

    bld.program(
        target = 'memAnalyzer',
        source = 'analyzer.cpp main.cpp',
        includes = '. ../runtime ' + elfInclude,
        use = 'utils BOOST BOOST_PROGRAM_OPTIONS BOOST_FILESYSTEM BOOST_SYSTEM'
    )
